name: Catkin Make (Build and Test)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: eteration/muto-ros:noetic-desktop-full
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          mkdir -p $(pwd)/tmp/muto/src/
          ln -s $(pwd) $(pwd)/tmp/muto/src/
          cd $(pwd)/tmp/muto
          git clone https://github.com/eclipse-muto/messages.git  src/messages
          git clone https://github.com/eclipse-muto/core.git   src/core
          . /opt/ros/noetic/setup.sh
          catkin_make
          . $(pwd)/devel/setup.sh
          catkin_make test || true
          catkin_test_results --all --verbose
        name: Build in ros container
